map $sent_http_content_type $expires {
  "text/html"                   epoch;
  "text/html; charset=utf-8"    epoch;
  default                       off;
}

server {
  listen 80 default_server;

  gzip on;
  gzip_types text/plain application/xml text/css application/javascript;
  gzip_min_length 1000;

  # API-прокси на Laravel (контейнер web_dto)
  location /api {
    rewrite ^/api/(.*)$ /$1 break;     # убираем /api из пути
    proxy_pass http://web_dto;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 60s;
    proxy_read_timeout 120s;
    proxy_send_timeout 60s;
  }

  location / {
    expires $expires;

    # WebSocket support (обязательно для HMR)
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_redirect off;
    proxy_connect_timeout 1m;
    proxy_read_timeout 86400;   # долгое соединение для WebSocket

    proxy_pass http://admin_nuxt:3000;   # исправлено имя контейнера
  }
}